apiVersion: apps/v1
kind: Deployment
metadata:
  name: zip-service-deployment
  namespace: default
  labels:
    app: zip-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zip-service
  template:
    metadata:
      labels:
        app: zip-service
    spec:
      containers:
      - name: zip-service
        image: konuratdocker/spark-examples:zipcode-service
        command: ["java"]
        args: ["-jar","/app.jar","8085"]
        ports:
        - containerPort: 8085
      nodeSelector:
        servicetype: zipcodeservice
      imagePullSecrets:
      - name: regcred 
      dnsConfig:
        nameservers:
          - 8.8.8.8
