apiVersion: v1
kind: Service
metadata:
  name: zipcode-service
  namespace: default
spec:
  ports:
  - port: 8085
    targetPort: 8085
    name: http
    protocol: TCP
  selector:
    app: zip-service
  type: ClusterIP
